cache:
  mount:
    - node_modules/

build:
  image: node
  commands:
    - npm -s i
    - npm test

notify:
  slack:
    webhook_url: https://hooks.slack.com/services/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
    channel: build
    username: drone


